### ISSUE TITLE
ModuleNotFoundError: No module named 'layers.discriminator'

### ISSUE THREAD

**Issue by Hichengdong** [litwellchi/BEV-SAN#3]
我在运行脚本 python exps/bev_depth_lss_r50_256x704_128x128_20e_cbgs_2key_da.py -b 2 --gpus 1
时发生了一个错误:
Traceback (most recent call last):
  File "exps/bev_depth_lss_r50_256x704_128x128_20e_cbgs_2key_da.py", line 33, in <module>
    from exps.bev_depth_lss_r50_256x704_128x128_24e_2key import \
  File "/home/cd/BEV-SAN/exps/bev_depth_lss_r50_256x704_128x128_24e_2key.py", line 30, in <module>
    from exps.bev_depth_lss_r50_256x704_128x128_24e_tshead import \
  File "/home/cd/BEV-SAN/exps/bev_depth_lss_r50_256x704_128x128_24e_tshead.py", line 23, in <module>
    from layers.discriminator.img_disc import Disc_img_source
ModuleNotFoundError: No module named 'layers.discriminator'

我在这个仓库和BEVDepth的仓库中都没有找到这个包。

**Comment by RoyZry98** [comment]
You may safely remove the 'layers.discriminator' module, as it is associated with a different project of ours and is not required for this particular task.

**Comment by Hichengdong** [comment]
> You may safely remove the 'layers.discriminator' module, as it is associated with a different project of ours and is not required for this particular task.

感谢！
